projet/app1/urls.py
from django.urls import path 

from app1.models import Produit, Fournisseur, Client, Employe, Centre
from . import views

urlpatterns = [ 
        # achat
path('acheter_matiere/create_fournisseur/', views.fournisseur_create_achat, name='fournisseur_create_achat'),
path('acheter_matiere/create_mp/', views.matiere_premiere_create_achat, name='matiere_premiere_create_achat'),
# path('delete_achat/<int:achat_id>/', views.delete_achat, name='delete_achat'),
# path('generate_journal_achat_pdf/', views.generate_journal_achat_pdf, name='generate_journal_achat_pdf'),
path('ajouter_achat/', views.ajouter_achat, name='ajouter_achat'),
path('journal_achat/', views.journal_achat, name='journal_achat'),
path('paiement/<int:achat_id>', views.payer_fournisseur, name='paiement'),
path('complete_paiement_fournisseur/', views.complete_paiement_fournisseur, name='complete_paiement_fournisseur'),
path('ajouter_achat/paiement/<int:achat_id>/', views.liste_paiement_achat, name='liste_paiement_achat'),
path('ajouter_achat/paiement/update/<int:pk>/', views.paiement_fournisseur_update, name='paiement_fournisseur_update'),
path('ajouter_achat/paiement/delete/<int:pk>/', views.paiement_fournisseur_delete, name='paiement_fournisseur_delete'),
        # Vente 
path('vendre/', views.vendre_matiere, name='vendre_matiere'),
path('vendre/create_client', views.client_create_vente, name='client_create_vente'),
path('paiement_credit/', views.paiement_credit, name='paiement_credit'),
path('journal_ventes/', views.journal_ventes, name='journal_ventes'),
path('vendre/paiement/<int:vente_id>/', views.liste_paiement_vente, name='liste_paiement_vente'),
# path('delete_vente/<int:vente_id>/', views.delete_vente, name='delete_vente'),
# path('journal_ventes/editer_vente/<int:pk>',views.update_vente,name='editer_vente'),
path('complete_paiement/', views.complete_paiement, name='complete_paiement'),
        #Transfert 
path('transfert/', views.transferer_matiere, name='transfert_matiere'),
path('journal_transferts/', views.journal_transferts, name='journal_transferts'),
                # MAJ models 
        #Fournisseur
path('fournisseurs/', views.fournisseur_list, name='fournisseur_list'),
path('fournisseurs/create/', views.fournisseur_create, name='fournisseur_create'),
path('fournisseurs/update/<int:pk>/', views.fournisseur_update, name='fournisseur_update'),
path('fournisseurs/delete/<int:pk>/', views.fournisseur_delete, name='fournisseur_delete'),
        #STOCK 
path('etat_stock/', views.etat_stock, name='etat_stock'),
path('generate_stock_pdf/', views.generate_stock_pdf, name='generate_stock_pdf'),
path('etat_stock/delete_stock/<int:stock_id>/', views.delete_stock, name='delete_stock'),
path('supprimer_stocks_zero/', views.supprimer_stocks_zero, name='supprimer_stocks_zero'),
        #matiere premiere
path('matiere_premiere_list/', views.matiere_premiere_list, name='matiere_premiere_list'),
path('matieres_premieres/create/', views.matiere_premiere_create, name='matiere_premiere_create'),
path('matieres_premieres/update/<int:pk>/', views.matiere_premiere_update, name='matiere_premiere_update'),
path('matieres_premieres/delete/<int:pk>/', views.matiere_premiere_delete, name='matiere_premiere_delete'),
        #Client
path('clients/', views.liste_clients, name='liste_clients'),
path('clients/create/', views.client_create, name='client_create'),
path('clients/update/<int:pk>/', views.client_update, name='client_update'),
path('clients/delete/<int:pk>/', views.client_delete, name='client_delete'),
        #Achat
path('update_achat/<int:pk>/', views.achat_update, name='achat_update'),
        #Vente
path('update/<int:pk>/', views.vente_update, name='vente_update'),
path('delete_vente/<int:pk>/', views.delete_vente, name='delete_vente'),
        #Paiement client
path('paiement/', views.liste_paiement, name='liste_paiement'),
path('paiement/create/', views.complete_paiement, name='complete_paiement'),
path('paiement/update/<int:pk>/', views.paiement_update, name='paiement_update'),
path('paiement/delete/<int:pk>/', views.paiement_delete, name='paiement_delete'),

#---------------Section 2-3-4----


#-----------Affichage home ----------------------
    path("", views.home, name="home"),
    path("mag/", views.afficher_BD, name="magasin"),
    path("mag/editer/<int:pk>", views.edit_BD, name="editer"),
  #-----------creation / modif / supppression ----------------------
    path("editer_client/<int:pk>/", views.editer_client, name="inserer_Client"),
    path("editer_employe/<int:pk>/", views.editer_employe, name="create_employe"),
    path("editer_produit/<int:pk>/", views.editer_produit, name="create_produit"),
    path("editer_Fournisseur/<int:pk>/", views.editer_fournisseur, name="inserer"),
    path("mag/create_employe/", views.create_employe, name="create_employe"),
    path("mag/create_produit/", views.create_produit, name="create_produit"),
    path("mag/insertFournisseur/", views.create_fournisseur, name="inserer"),
    path("mag/insertClient/", views.create_client, name="inserer_Client"),
    path("supprimer_client/<int:pk>/",views.delete_BD,{"model_name": Client},name="supprimer_client",),
    path("supprimer_produit/<int:pk>/",views.delete_BD,{"model_name": Produit},name="supprimer_produit",),
    path("supprimer_centre/<int:pk>/",views.delete_BD,{"model_name": Centre,},name="supprimer_centre",),
    path("supprimer_employe/<int:pk>/",views.delete_BD,{"model_name": Employe},name="supprimer_employe",),
    path("supprimer_fournisseur/<int:pk>/",views.delete_BD,{"model_name": Fournisseur},name="supprimer_fournisseur",),
   
    path('reglement_credit_client/<int:vente_id>/', views.reglement_credit_client, name='reglement_credit_client'),
    path("vendre_produit/<int:centre_id>/", views.vendre_produit, name="vendre_produit"),
    path("centre/<int:centre_id>/", views.detail_centre, name="centre"),
    path("employe/<int:employe_id>/", views.detail_employe, name="detail_employe"),
    path("paiement-employe/<int:employe_id>/",views.saisir_paiement,name="paiement_employe"),
    path("paiement-calcule/<int:employe_id>/", views.calcul_salaire, name="calcul_salaire"),
    path('journal_vente_produit/<int:centre_id>/', views.Journal_Vente_Produit, name='Journal_Vente_Produit'),
    path('modify_absence/<int:employe_id>/', views.modify_absence, name='modify_absence'),
    path('client/<int:client_id>/', views.detail_client, name='client_detail'),
    path('vente/<int:vente_id>/supprimer/', views.supprimer_vente, name='supprimer_vente'),
    path('stock_state/<int:centre_id>/', views.stock_state, name='stock_state'),
    path('add_produit_to_stock/<int:centre_id>/', views.add_produit_to_stock, name='Produit'),
    path('calcul_ventes_nettes/<int:centre_id>/', views.calcul_ventes_nettes, name='calcul_ventes_nettes'),
    path('calculer_benefice/<int:centre_id>/', views.calculer_benefice, name='calculer_benefice'),
   
    path('detail_produit/<int:pk>/', views.detail_produit, name='detail_produit'),
    path('journal_transferts-centre/<int:centre_id>/', views.journal_transfert_c, name='journal_transferts'),


#-------------SECTION  5----
path('analyze-achats/', views.analyze_achats, name='analyze_achats'),
   path('dashboard_ventes/', views.dashboard_ventes, name='dashboard_ventes'),
    path('vente_data/', views.vente_data, name='vente_data'),
    path('taux_evolution_benefice/', views.taux_evolution_benefice, name='taux_evolution_benefice'),
    path('top_clients/', views.top_clients, name='top_clients'),
    path('best_selling_products/', views.best_selling_products, name='best_selling_products'),

]

projet/projet/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app1.urls")),
]

projet/app1/models.py
from ctypes.wintypes import HINSTANCE
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.dispatch import receiver


class Centre(models.Model):
    code=models.CharField(max_length=100)
    designation = models.CharField(max_length=100)

class Client(models.Model):
    nom = models.CharField(max_length=100)
    prenom = models.CharField(max_length=100)
    adresse = models.TextField()
    telephone = models.CharField(max_length=15)
    credit = models.DecimalField(max_digits=10, decimal_places=2)
    # def __str__(self):

class Fournisseur(models.Model):
    nom = models.CharField(max_length=100)
    prenom = models.CharField(max_length=100)
    adresse = models.TextField()
    telephone = models.CharField(max_length=15)
    solde = models.DecimalField(max_digits=10, decimal_places=2 ,default=0)

class Employe(models.Model):
    nom = models.CharField(max_length=100)
    prenom = models.CharField(max_length=100)
    adresse = models.TextField()
    telephone = models.CharField(max_length=15)
    salaire_jour = models.DecimalField(max_digits=10, decimal_places=2)
    centre = models.ForeignKey(Centre, on_delete=models.CASCADE)

class Matiere_premiere(models.Model):
    designation = models.CharField(max_length=100)
 
class Produit(models.Model):
    designation = models.CharField(max_length=100)
    matiere_quantite = models.JSONField(null=True, blank=True)
 

class Achat(models.Model):
    fournisseur = models.ForeignKey(Fournisseur, on_delete=models.CASCADE)
    matiere = models.ForeignKey(Matiere_premiere, on_delete=models.CASCADE, null=True)
    quantite = models.PositiveIntegerField()
    prix_unitaire_HT = models.DecimalField(max_digits=10, decimal_places=2)
    date_achat = models.DateField()
    @property
    def montant_achat(self):
        return self.quantite * self.prix_unitaire_HT

class Reglement(models.Model):
    achat = models.ForeignKey(Achat, on_delete=models.CASCADE,null=True)
    montant = models.DecimalField(max_digits=10, decimal_places=2)
    date_reglement = models.DateField()


class Vente(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    matiere = models.ForeignKey(Matiere_premiere, on_delete=models.CASCADE, null=True)
    quantite = models.PositiveIntegerField()
    prix_unitaire = models.DecimalField(max_digits=10, decimal_places=2)
    date_vente = models.DateField()

    @property
    def montant_vente(self):
        return self.quantite * self.prix_unitaire

class paiementcredit(models.Model):
    vente = models.ForeignKey(Vente, on_delete=models.CASCADE, null=True)
    montant = models.DecimalField(max_digits=10, decimal_places=2)
    date_paiement_credit = models.DateField()

class Transfert(models.Model):
    date_transfert = models.DateField()
    centre_dest = models.ForeignKey(Centre, on_delete=models.CASCADE)
    matiere = models.ForeignKey(Matiere_premiere, on_delete=models.CASCADE,null=True)
    quantite = models.PositiveIntegerField()
    cout_transfert = models.DecimalField(max_digits=10, decimal_places=2, editable=False)


class Stock(models.Model):
    matiere = models.ForeignKey(Matiere_premiere, on_delete=models.CASCADE, null=True)
    quantite = models.PositiveIntegerField()
    fournisseur  = models.ForeignKey(Fournisseur, on_delete=models.CASCADE)
    date_achat = models.DateField(null=True)
    prix = models.DecimalField(max_digits=10, decimal_places=2)
 
class stock_Produit(models.Model):
    produit = models.ForeignKey(Produit, on_delete=models.CASCADE)
    centre = models.ForeignKey(Centre, on_delete=models.CASCADE)
    quantite = models.DecimalField(max_digits=15, decimal_places=2)
  
class stock_Matiere(models.Model):
    Matiere_premiere = models.ForeignKey(Matiere_premiere, on_delete=models.CASCADE)
    centre = models.ForeignKey(Centre, on_delete=models.CASCADE)
    quantite = models.DecimalField(max_digits=15, decimal_places=2)
 

class Vente_Produit(models.Model):
    date_vente = models.DateField()
    code = models.CharField(max_length=10, unique=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE,related_name='vente_produits')
    centre = models.ForeignKey(Centre, on_delete=models.CASCADE)
    produit = models.ForeignKey(Produit, on_delete=models.CASCADE)
    quantite = models.PositiveIntegerField()
    prix_unitaire = models.DecimalField(max_digits=10, decimal_places=2)
    montant_total = models.DecimalField(
        max_digits=10, decimal_places=2, blank=True, null=True
    )
    montant_verse = models.DecimalField(
        max_digits=10, decimal_places=2, default=0, blank=True, null=True
    )
    credit = models.DecimalField(
        max_digits=10, decimal_places=2, default=0, blank=True, null=True
    )
 
class PaiementCreditCentre(models.Model):
    centre = models.ForeignKey(Centre, on_delete=models.CASCADE)
    vente = models.ForeignKey(Vente_Produit, on_delete=models.CASCADE)
    montant = models.DecimalField(max_digits=10, decimal_places=2)
    date_paiement_credit = models.DateField(auto_now_add=True)

from django.utils import timezone

class Paiement_E(models.Model):
    date_paiement = models.DateField(default=timezone.now)
    employe = models.ForeignKey(Employe, on_delete=models.CASCADE)
    montant = models.DecimalField(max_digits=10, decimal_places=2, default=0) #salir_jour
    avance = models.DecimalField(max_digits=10, decimal_places=2, default=0) #Massrouf
    absence = models.BooleanField(default=False)   

projet/app1/templates/complete_paiement.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
</head>
<link rel="stylesheet" href="{% static 'css/css.css' %}">

<body>
    <!-- complete le paiement du credit client  -->
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <a href="{% url 'journal_ventes' %}"> Annuler</a>
        <input type="submit" value="Valider">
    </form>


</body>

</html>

projet/app1/templates/complete_paiement_fournisseur.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
</head>
<link rel="stylesheet" href="{% static 'css/css.css' %}">

<body>
    <!-- complete le paiement du solde fournisseur  -->
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <a href="{% url 'journal_achat' %}"> Annuler</a>
        <input type="submit" value="Valider">
    </form>


</body>

</html>

projet/app1/templates/create_produit.html
<!DOCTYPE html>

{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Créer Produit</title>
    <link rel="stylesheet" href="{% static 'css/css.css' %}">

</head>
<body>

<!-- create_produit.html -->
<form method="post" action="{% url 'create_produit' %}">
    {% csrf_token %}
    {{ form.as_p }}  <!-- Affichage du formulaire, y compris le champ 'matieres' -->
    <input type="submit" value="Enregistrer">
  </form>
  
</body>
</html>

projet/app1/templates/detail_produit.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/css.css' %}">

    <title>Document</title>
</head>
<body>
    <h1>Detail Produit</h1>

    
    <p><strong>Produit:</strong> {{ produit.designation }}</p>
    <p><strong>Matiere-Quantite:</strong></p>
    <table border="1">
        <thead>
            <tr>
                <th>Matiere</th>
                <th>Quantite</th>
            </tr>
        </thead>
        <tbody>
            {% for info in matiere_quantite_info %}
                <tr>
                    <td>{{ info.matiere.designation }}</td>
                    <td>{{ info.quantite }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    
    <a href="{% url 'magasin'  %}">Retour à l'accueil</a>

    

  



</body>
</html>

projet/app1/templates/editer.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Détails de l'employé</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/css.css' %}?v=2">


  </head>
<!-- editer employer     -->
<body>
   
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p}}
        <a href=" {% url 'magasin' %}"> Annuler</a>
        <!-- pour revenir en arrière et annuler la modification -->
        <input type="submit" value="Modifier">
    </form>
</body>

</html>

projet/app1/templates/inserer.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/css.css' %}" />

</head>
<body>
    <form method="POST" >
        {% csrf_token %}
        {{ form.as_p }}
        <a href="{% url 'magasin' %}"> Annuler</a>
        
        <input type="submit" value="Valider">
    </form>

</body>

</html>

projet/app1/templates/journal_achat.html
<!-- Créez un fichier HTML nommé journal_achat.html dans votre dossier templates -->

<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Journal des Achats</title>
    <!-- link to compiled css file -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/nav.css' %}">
</head>

<body>
    <style>
        

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f1f1f1;
  min-width: 160px;
  z-index: 1;
}

.dropdown-content a {
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}

.dropdown-content a:hover {background-color: #ddd;}

.dropdown:hover .dropdown-content {display: block;}
.dropdown button {
    border: none;
    font-size: 3vh;
}
main a{
                text-decoration:none;
            }
            .btn-outline-success a {
                color: green;
            }
            .btn-outline-success a:hover {
                color: white;
            }
            .btn-outline-danger a {
                color: red;
            }
            .btn-outline-danger a:hover {
                color: white;
            }
            .btn-outline-primary a:hover{
                color: white;
            }
            .filter input{
                display: block;}
            #first_row{
                display: flex;
                align-items: center;
                justify-content: space-between;
                margin: 3vh;
            }


    </style>
    
    
    
    <nav class="navbar">
        <ul>
            <img src="/project1/app1/templates/Logo.png" alt="logo">
            <li><a href="{% url 'analyze_achats' %}">Dashboard</a></li>
            <li>
                <div class="dropdown">
                    <button class="dropbtn">Tables</button>
                    <div class="dropdown-content">
                        <a href="{% url 'liste_clients' %}">Liste clients</a>
                        <a href="{% url 'fournisseur_list' %}">Liste Fournisseur</a>
                        <a href="{% url 'matiere_premiere_list' %}">Liste Matières Premières</a>
                        <a href="{% url 'journal_achat' %}">Journal Achat</a>
                        <a href="{% url 'journal_ventes' %}">Journal Vente</a>
                        <a href="{% url 'journal_transferts' %}">Journal Transfert</a>
                        <a href="{% url 'etat_stock' %}">Etat Stock</a>
                    </div>
                </div>
            </li>
            <li><a href="#">Acheter</a></li>
            <li><a href="#">Vendre</a></li>
            <li><a href="#">Transferer</a></li>
            <li><a href="#">Stock</a></li>
            <li><a href="#">Account</a></li>
            <li><a href="#">Security</a></li>
            <li><a href="#">Help Center</a></li>
        </ul>
    </nav>
    
    <main class="content">
        <div id="first_row">
            <h1>Journal des Achats</h1>
            <h4><a href="{% url 'ajouter_achat'  %}"> nouvel achat </a></h4>
            <h4><a href="{% url 'complete_paiement_fournisseur'  %}"> compléter paiement </a></h4>
        </div>

    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Numero d'achat</th>
                <th>Fournisseur</th>
                <th>Matière première</th>
                <th>Quantité</th>
                <th>Prix unitaire HT</th>
                <th>Prix total</th>
                <th>Date d'achat</th>
            </tr>
        </thead>
        <tbody>
            {% for achat in achats %}
            <tr>
                <td>{{ achat.id }}</td>
                <td>{{ achat.fournisseur.nom }}</td>
                <td>{{ achat.matiere.designation }}</td>
                <td>{{ achat.quantite }}</td>
                <td>{{ achat.prix_unitaire_HT }}</td>
                <td>{{ achat.montant_achat }}</td>
                <td>{{ achat.date_achat }}</td>
                <td><button type="button" class="btn btn-outline-success"><a href="{% url 'achat_update' pk=achat.pk %}"> Edit </a></button></td>
                <td><button type="button" class="btn btn-outline-danger"><a href="#"> Delete </a></button></td>
                <!-- <td><a href="#" onclick="confirmDelete('{{ vente.id }}')">Supprimer</a></td> -->
                <td><button type="button" class="btn btn-outline-primary"><a href="{% url 'liste_paiement_achat' achat_id=achat.pk  %}">
                        detail</a></button></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    
    
    <script>
        function confirmDelete(venteId) {
            console.log("vente ID:", venteId);
            var result = confirm("Voulez-vous vraiment supprimer cet vente?");
            if (result && venteId) {
                var deleteUrl = "/delete_vente/" + venteId + "/";
                window.location.href = deleteUrl;
            }
        }
    </script>
    </main>

    <div class="filter">
        <p>Total des Achats: {{ total_achats }}</p>
        <form method="GET" action="{% url 'journal_achat' %}">
            <label for="fournisseur">Fournisseur Name:</label>
            <input type="text" name="fournisseur">
    
            <label for="matiere_name">Matiere Name:</label>
            <input type="text" name="matiere_name">
    
            <label for="date_achat">Date achat:</label>
            <input type="date" name="date_achat">
    
            <input type="submit" value="Filter" class="btn btn-outline-info">
        </form>
    </div>
    <!-- link to compiled js file -->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"> </script>
</body>

</html>

projet/app1/templates/journal_transferts.html
<!DOCTYPE html>
<html>

<head>
    <!-- Ajoutez vos balises head ici -->
</head>

<body>
    <h1>Journal des Transferts</h1>
    <table>
        <thead>
            <tr>
                <th>Date Transfert</th>
                <th>Centre Destination</th>
                <th>Matiere</th>
                <th>Quantité</th>
                <th>Coût Transfert</th>
            </tr>
        </thead>
        <tbody>
            {% for transfert in transferts %}
            <tr>
                <td>{{ transfert.date_transfert }}</td>
                <td>{{ transfert.centre_dest.designation }}</td>
                <td>{{ transfert.matiere.designation }}</td>
                <td>{{ transfert.quantite }}</td>
                <td>{{ transfert.cout_transfert }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <p>Total des Transferts: {{ total_transferts }}</p>
</body>

</html>

projet/app1/templates/liste_paiement_fournisseur.html
<!-- tous les paiement effectues par le client  -->
<!DOCTYPE html>
<html>

<head>
    <title>Paiement List Fournisseur</title>
</head>

<body>
    <h2>Paiement List Fournisseur</h2>
    <h3>crédit de cet achat : {{montant_restant}}</h3>
    <table>
        <thead>
            <tr>
                <th>Numéro Achat</th>
                <th>Numéro Fournisseur </th>
                <th>Nom Fournisseur</th>
                <th>Prénom Fournisseur</th>
                <th>Date paiement</th>
                <th>Matière achetée</th>
                <th>Montant payé</th>
            </tr>
        </thead>
        <tbody>
            {% for paiement in paiement %}
            <tr>
                <td>{{paiement.achat.id}}</td>
                <td>{{paiement.achat.fournisseur.id}}</td>
                <td>{{paiement.achat.fournisseur.nom}}</td>
                <td>{{paiement.achat.fournisseur.prenom }}</td>
                <td>{{paiement.date_reglement }}</td>
                <td>{{paiement.achat.matiere.designation }}</td>
                <td>{{paiement.montant }}</td>
                <td><a href="{% url 'paiement_fournisseur_update' pk=paiement.pk %}">Update</a></td>
                <td><a href="{% url 'paiement_fournisseur_delete' pk=paiement.pk %}">Delete</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    </ul>
    <a href="{% url 'complete_paiement_fournisseur' %}">complete paiement</a>
</body>

</html>

projet/app1/templates/matiere_premiere_form.html
<!-- templates/matiere_premiere_form.html -->
<!DOCTYPE html>
<html>

<head>
    <title>Matiere Premiere Form</title>
</head>

<body>
    <h2>Matiere Premiere Form</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
    <a href="{% url 'matiere_premiere_list' %}">Back to Matiere Premiere List</a>
</body>

</html>

projet/app1/templates/paiement_credit.html
<!DOCTYPE html>
<html>

<head>
</head>

<body>
    <!-- paiement_credit.html -->
    <h3>montant total : $$$$</h3>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <a href="{% url 'journal_ventes' %}"> Annuler</a>
        <input type="submit" value="Valider">
    </form>


</body>

</html>

projet/app1/templates/transferer_matiere.html
<!DOCTYPE html>
<html>

<head>
    <!-- Ajoutez vos balises head ici -->
</head>

<body>
    <h1>Transférer des Matières</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <h5>{{message}}</h5>
        <input type="submit" value="Transférer">
    </form>
</body>

</html>

projet/app1/templates/update_achat.html
<!-- templates/achats/update_achat.html -->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Modifier un Achat</title>
</head>

<body>
    <h1>Modifier un Achat</h1>

    <form method="post" action="{% url 'achat_update' pk=achat.pk %}">
        {% csrf_token %}

        <!-- Hidden input for the primary key -->
        <input type="hidden" name="pk" value="{{ achat.pk }}">

        <!-- Champs pour le formulaire -->
        {{ form.as_p }}

        <!-- Bouton de soumission -->
        <button type="submit">Modifier Achat</button>
    </form>

    <a href="{% url 'journal_achat' %}">Retour au Journal des Achats</a>
</body>

</html>

projet/app1/templates/vendre_matiere.html
<!DOCTYPE html>
<html>

<head>
</head>

<body>
    <!-- vendre_matiere.html -->
    <form method="POST">
        {% csrf_token %}
        <!-- recuperer le nom du fournisseur -->
        <div>
            <label for="id_client">Client:</label>
            <select id="id_client" name="client">
                {% for client in clients %}
                <option value="{{ client.id }}">{{ client.nom }}</option>
                {% endfor %}
            </select>
            <a href=" {% url 'client_create_vente' %}"> ADD </a>
        </div>

        <div>
            <label for="id_date_vente">Date:</label>
            <input type="date" name="date_vente" required>
        </div>
        <!-- recuperer le nom (designation) du produit -->
        <div>
            <label for="id_matiere">matiere:</label>
            <select id="id_matiere" name="matiere">

                {% for matiere in matieres %}
                <option value="{{ matiere.id }}">{{ matiere.designation }}</option>
                {% endfor %}
            </select>
        </div>

        <!-- inserer la quantite achetee -->
        <div>
            <label for="id_quantite">Quantité:</label>
            <input type="number" name="quantite" required>
        </div>

        <!-- inserer le prix unitaire d'achat -->
        <div>
            <label for="id_prix_unitaire">Prix unitaire:</label>
            <input type="number" name="prix_unitaire" required>
        </div>
        <a href="{% url 'journal_ventes' %}"> Annuler</a>
        <input type="submit" value="Valider">
    </form>

</body>

</html>